/**
 * Every user-facing string in the app. Components must never inline text.
 *
 * Grouped by the screen or component that renders them, so a translator (or a
 * future i18n layer) can move a whole group at once.
 */
export const STRINGS = {
  app: {
    title: 'Nhà Trọ An Cư',
    tagline: 'Hệ thống quản lý phòng trọ thông minh',
    shortName: 'An Cư',
  },
  health: {
    checking: 'Đang kiểm tra máy chủ…',
    online: 'Máy chủ hoạt động',
    offline: 'Không kết nối được máy chủ — backend đã chạy chưa?',
    versionLabel: 'phiên bản',
  },
  common: {
    save: 'Lưu',
    saving: 'Đang lưu…',
    cancel: 'Hủy',
    close: 'Đóng',
    edit: 'Sửa',
    delete: 'Xóa',
    deleting: 'Đang xóa…',
    confirmDelete: 'Bạn chắc chắn muốn xóa mục này?',
    add: 'Thêm',
    search: 'Tìm kiếm',
    loading: 'Đang tải…',
    retry: 'Thử lại',
    empty: 'Chưa có dữ liệu.',
    all: 'Tất cả',
    actions: 'Thao tác',
    submitting: 'Đang gửi…',
    updating: 'Đang cập nhật…',
    required: 'Bắt buộc',
    optional: 'Không bắt buộc',
    currencySuffix: 'đ',
    perMonth: '/tháng',
    unknown: '—',
  },
  nav: {
    menu: 'Menu',
    home: 'Trang chủ',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    register: 'Đăng ký',
    adminArea: 'Trang quản trị',
    tenantArea: 'Cổng khách thuê',
    dashboard: 'Tổng quan',
    rooms: 'Quản lý phòng',
    contracts: 'Hợp đồng',
    meters: 'Ghi chỉ số',
    invoices: 'Hóa đơn',
    services: 'Bảng giá dịch vụ',
    users: 'Người dùng',
    leads: 'Yêu cầu tư vấn',
  },
  home: {
    heroEyebrow: 'Phú Đô, Từ Liêm — cách Mỹ Đình 900 m',
    heroTitle: 'Chỗ ở tử tế, chi phí rõ ràng.',
    heroBody:
      'Phòng đầy đủ nội thất, an ninh 24/7, internet cáp quang riêng từng phòng. Điện nước tính theo công tơ riêng và có hoá đơn chi tiết gửi qua email mỗi tháng.',
    heroImageAlt: 'Phòng cho thuê đã hoàn thiện nội thất',
    heroPrimaryAction: 'Xem phòng còn trống',
    heroSecondaryAction: 'Đặt lịch xem phòng',
    amenitiesHeading: 'Tiện ích cốt lõi',
    amenitiesBody: 'Ba thứ chúng tôi đầu tư trước khi nghĩ tới bất cứ điều gì khác.',
    fireTitle: 'Hệ thống PCCC đạt chuẩn',
    fireBody:
      'Cảm biến khói tự động từng tầng, vòi phun nước ngầm, lối thoát hiểm thông suốt và bình chữa cháy được kiểm định định kỳ.',
    internetTitle: 'Internet cáp quang & Wifi',
    internetBody:
      'Hạ tầng cáp quang riêng cho từng phòng, băng thông cam kết ổn định, Wifi phủ sóng toàn tòa nhà cho làm việc và giải trí.',
    otherTitle: 'An ninh & tiện ích chung',
    otherBody:
      'Khu để xe có camera 24/7 và khóa vân tay, dịch vụ vệ sinh không gian chung, khu giặt sấy ngay trong tòa nhà.',
    heroChipFire: 'PCCC đạt chuẩn',
    heroChipInternet: 'Cáp quang riêng phòng',
    heroChipSecurity: 'Camera 24/7',
    bandEyebrow: 'Toà nhà',
    bandTitle: 'Ngõ ô tô tránh, cách Sân Vận Động Mỹ Đình 900 m.',
    bandBody:
      'Chín tầng, thang bộ rộng, hành lang có đèn cảm ứng. Đi bộ 5 phút ra Công Viên Mễ Trì, 10 phút tới Sân Vận Động Mỹ Đình.',
    statRooms: 'Phòng đang đăng',
    statAvailable: 'Phòng còn trống',
    statFromPrice: 'Giá thuê từ',
    statMaxArea: 'Diện tích tới',
    extrasHeading: 'Và những thứ nhỏ hơn nhưng dùng hằng ngày',
    extraParking: 'Bãi xe khoá vân tay',
    extraCamera: 'Camera hành lang 24/7',
    extraCleaning: 'Vệ sinh khu chung hằng tuần',
    extraLaundry: 'Máy giặt sấy dùng chung',
    filterTypeLabel: 'Loại phòng',
    filterStatusLabel: 'Trạng thái',
    filterEmpty: 'Không có phòng nào khớp bộ lọc. Thử bỏ bớt một điều kiện.',
    filterCount: 'phòng phù hợp',
    processHeading: 'Thuê phòng ở đây gồm bốn bước',
    processBody: 'Không có bước nào phát sinh chi phí ngoài hợp đồng.',
    step1Title: 'Chọn phòng',
    step1Body:
      'Xem ảnh thật, diện tích và giá thuê ngay trên trang này. Không có phòng nào đăng giá khác giá ký.',
    step2Title: 'Xem phòng thực tế',
    step2Body:
      'Để lại số điện thoại, chúng tôi gọi lại trong ngày và hẹn giờ bạn tiện. Xem cả phòng lẫn khu để xe, khu giặt.',
    step3Title: 'Ký hợp đồng',
    step3Body:
      'Hợp đồng ghi rõ ngày bắt đầu, tiền cọc, kỳ thanh toán và đơn giá điện nước đang áp dụng.',
    step4Title: 'Nhận tài khoản theo dõi',
    step4Body:
      'Ngay khi ký, hệ thống gửi email xác thực kèm tài khoản riêng. Đăng nhập là xem lại được mọi kỳ hoá đơn đã chốt.',
    faqHeading: 'Hỏi nhanh, đáp thẳng',
    faqBody: 'Những câu khách hay hỏi nhất khi gọi tới.',
    faq1Q: 'Tiền điện nước tính thế nào?',
    faq1A:
      'Theo chỉ số công tơ riêng của từng phòng. Mỗi kỳ hệ thống ghi lại chỉ số cũ, chỉ số mới, đơn giá và thành tiền — đúng bảng bạn thấy ở đầu trang. Đơn giá tại thời điểm xuất hoá đơn được lưu lại, nên bảng giá đổi về sau không làm thay đổi hoá đơn đã phát hành.',
    faq2Q: 'Đặt cọc bao nhiêu và khi nào được trả lại?',
    faq2A:
      'Cọc một tháng tiền phòng, ghi trong hợp đồng. Trả lại khi thanh lý hợp đồng, sau khi trừ hoá đơn kỳ cuối và chi phí hư hỏng nếu có.',
    faq3Q: 'Hợp đồng tối thiểu bao lâu?',
    faq3A:
      'Sáu tháng. Hệ thống nhắc trước 30 ngày khi hợp đồng sắp hết hạn, nên không có chuyện tới ngày mới biết.',
    faq4Q: 'Có giờ giới nghiêm không?',
    faq4A:
      'Không. Cửa chính dùng khoá vân tay, ra vào giờ nào cũng được. Chỉ đề nghị giữ yên tĩnh sau 23h.',
    faq5Q: 'Có được nuôi thú cưng, nấu ăn trong phòng không?',
    faq5A:
      'Nấu ăn được, mỗi phòng có khu bếp riêng và quạt hút. Thú cưng nhỏ được, cần báo trước để ghi vào hợp đồng.',
    faq6Q: 'Thanh toán bằng cách nào?',
    faq6A:
      'Chuyển khoản theo hoá đơn gửi qua email đầu mỗi kỳ. Hoá đơn ghi rõ đã trả bao nhiêu, còn lại bao nhiêu, không cần hỏi lại.',
    roomsHeading: 'Phòng mẫu',
    roomsBody: 'Bấm vào một phòng để xem toàn bộ hình ảnh và thông tin chi tiết.',
    roomsEmpty: 'Hiện chưa có phòng nào được đăng.',
    contactHeading: 'Đăng ký giữ chỗ',
    contactBody:
      'Để lại thông tin, chúng tôi sẽ gọi lại trong ngày để hẹn lịch xem phòng.',
    contactAddressLabel: 'Địa chỉ',
    contactAddress: 'Ngõ 8/75 Phú Đô, Từ Liêm, Hà Nội',
    contactPhoneLabel: 'Gọi trực tiếp',
    contactPhone: '0912 345 678',
    contactHoursLabel: 'Giờ xem phòng',
    contactHours: 'Thứ 2 – Chủ nhật, 8:00 – 20:00',
    contactPromise: 'Gọi lại trong ngày. Không nhắn tin quảng cáo, không chuyển số cho bên thứ ba.',
    footerNote: 'Hệ thống quản lý phòng trọ thông minh.',
    footerAboutHeading: 'Về nhà trọ',
    footerAbout:
      'Một toà nhà cho thuê ở Từ Liêm, vận hành bằng chính hệ thống này: chỉ số điện nước, hợp đồng và hoá đơn đều ghi lại được.',
    footerLinksHeading: 'Xem nhanh',
    footerContactHeading: 'Liên hệ',
    footerRights: 'Mọi quyền được bảo lưu.',
  },
  room: {
    areaLabel: 'Diện tích',
    areaUnit: 'm²',
    floorLabel: 'Tầng',
    typeLabel: 'Loại phòng',
    priceLabel: 'Giá thuê',
    amenitiesLabel: 'Tiện nghi',
    numberLabel: 'Số phòng',
    statusLabel: 'Trạng thái',
    descriptionLabel: 'Mô tả',
    imagesLabel: 'Bộ sưu tập ảnh',
    imageUrlPlaceholder: 'Dán link ảnh rồi bấm Thêm',
    addImage: 'Thêm ảnh',
    removeImage: 'Xóa ảnh',
    suggestedImages: 'Ảnh gợi ý',
    noImages: 'Chưa có ảnh nào.',
    detailHeading: 'Chi tiết phòng',
    bookThisRoom: 'Đặt lịch xem phòng này',
    galleryPrev: 'Ảnh trước',
    galleryNext: 'Ảnh sau',
    heading: 'Danh sách phòng',
    addAction: 'Thêm phòng',
    editAction: 'Sửa phòng',
    empty: 'Chưa có phòng nào. Thêm phòng đầu tiên.',
    searchPlaceholder: 'Tìm theo số phòng…',
    deleteConfirm: 'Xóa phòng này? Thao tác không thể hoàn tác.',
  },
  roomStatus: {
    available: 'Còn trống',
    occupied: 'Đang thuê',
    maintenance: 'Bảo trì',
    overdue: 'Chậm đóng tiền',
  },
  roomType: {
    studio: 'Studio',
    oneBedroom: '1 phòng ngủ',
    twoBedroom: '2 phòng ngủ',
  },
  auth: {
    loginHeading: 'Đăng nhập',
    loginBody: 'Dành cho quản trị viên và khách thuê đã xác minh email.',
    registerHeading: 'Đăng ký tài khoản quản trị',
    registerBody: 'Tạo tài khoản quản trị viên để truy cập hệ thống.',
    usernameLabel: 'Tên đăng nhập',
    usernamePlaceholder: 'vd: quanly01',
    emailLabel: 'Email',
    emailPlaceholder: 'ban@example.com',
    passwordLabel: 'Mật khẩu',
    passwordPlaceholder: 'Tối thiểu 6 ký tự',
    loginAction: 'Đăng nhập',
    loggingIn: 'Đang đăng nhập…',
    registerAction: 'Tạo tài khoản',
    registering: 'Đang tạo tài khoản…',
    toRegister: 'Chưa có tài khoản? Đăng ký',
    toLogin: 'Đã có tài khoản? Đăng nhập',
    signedInAs: 'Đang đăng nhập',
    verifyHeading: 'Xác minh email',
    verifying: 'Đang xác minh…',
    verifySuccess: 'Email đã được xác minh. Bạn có thể đăng nhập ngay.',
    verifyMissingToken: 'Liên kết xác minh không hợp lệ.',
    goToLogin: 'Tới trang đăng nhập',
    resendAction: 'Gửi lại email xác minh',
    resending: 'Đang gửi…',
    resendSent: 'Đã gửi lại email xác minh.',
  },
  role: {
    admin: 'Quản trị viên',
    manager: 'Quản lý',
    tenant: 'Khách thuê',
  },
  dashboard: {
    heading: 'Tổng quan kinh doanh',
    subtitle: 'Tình hình phòng ốc và dòng tiền theo thời gian thực.',
    totalRooms: 'Tổng số phòng',
    availableRooms: 'Phòng trống',
    occupiedRooms: 'Đang cho thuê',
    maintenanceRooms: 'Đang bảo trì',
    activeContracts: 'Hợp đồng hiệu lực',
    expiringContracts: 'Sắp hết hạn',
    unpaidInvoices: 'Hóa đơn chưa thu',
    outstandingAmount: 'Công nợ còn lại',
    monthRevenue: 'Doanh thu tháng này',
    gridHeading: 'Sơ đồ phòng',
    gridLegend: 'Chú thích',
    gridEmpty: 'Chưa có phòng nào để hiển thị.',
    revenueHeading: 'Doanh thu theo tháng',
    revenueRoom: 'Tiền phòng',
    revenueService: 'Tiền dịch vụ',
    revenueCollected: 'Đã thu',
    rangeMonth: 'Tháng này',
    rangeQuarter: 'Quý này',
    rangeYear: '12 tháng gần nhất',
    tenantLabel: 'Khách thuê',
    contractEndLabel: 'Hạn hợp đồng',
    vacant: 'Đang trống',
  },
  contract: {
    heading: 'Hợp đồng cho thuê',
    addAction: 'Tạo hợp đồng',
    editAction: 'Sửa hợp đồng',
    empty: 'Chưa có hợp đồng nào.',
    roomLabel: 'Phòng',
    tenantNameLabel: 'Họ tên khách thuê',
    idCardLabel: 'Số CCCD',
    phoneLabel: 'Số điện thoại',
    emailLabel: 'Email',
    startLabel: 'Ngày bắt đầu',
    endLabel: 'Ngày hết hạn',
    depositLabel: 'Tiền cọc',
    cycleLabel: 'Kỳ thanh toán',
    occupantsLabel: 'Số người ở',
    noteLabel: 'Ghi chú',
    statusLabel: 'Trạng thái',
    emailVerified: 'Email đã xác minh',
    emailUnverified: 'Email chưa xác minh',
    deleteConfirm: 'Thanh lý và xóa hợp đồng này? Phòng sẽ trở về trạng thái trống.',
    selectRoom: 'Chọn phòng',
    accountNote:
      'Hệ thống sẽ tự tạo tài khoản khách thuê: đăng nhập bằng email, mật khẩu mặc định là số điện thoại.',
  },
  contractStatus: {
    active: 'Đang hiệu lực',
    expiring: 'Sắp hết hạn',
    terminated: 'Đã thanh lý',
    overdue: 'Quá hạn đóng tiền',
  },
  paymentCycle: {
    monthly: 'Hàng tháng',
    quarterly: 'Mỗi 3 tháng',
  },
  meter: {
    heading: 'Ghi chỉ số điện nước',
    subtitle: 'Nhập chỉ số cuối kỳ cho từng phòng. Hóa đơn được tạo ngay khi ghi đủ hai chỉ số.',
    periodLabel: 'Kỳ ghi',
    searchPlaceholder: 'Tìm theo số phòng hoặc tên khách…',
    columnRoom: 'Phòng',
    columnTenant: 'Khách thuê',
    columnElectric: 'Điện (kWh)',
    columnWater: 'Nước (m³)',
    oldLabel: 'Cũ',
    newLabel: 'Mới',
    usageLabel: 'Tiêu thụ',
    saveAction: 'Lưu',
    savedLabel: 'Đã lưu',
    invoiceCreated: 'Đã tạo hóa đơn',
    empty: 'Không có phòng nào khớp bộ lọc.',
    tabAll: 'Tất cả',
    tabMissingElectric: 'Chưa ghi Điện',
    tabMissingWater: 'Chưa ghi Nước',
    tabComplete: 'Đã ghi xong',
    belowPrevious: 'Chỉ số mới không được nhỏ hơn chỉ số cũ.',
  },
  invoice: {
    heading: 'Hóa đơn',
    empty: 'Chưa có hóa đơn nào.',
    columnRoom: 'Phòng',
    columnTenant: 'Khách thuê',
    columnPeriod: 'Kỳ',
    columnTotal: 'Tổng tiền',
    columnPaid: 'Đã thanh toán',
    columnStatus: 'Trạng thái',
    detailHeading: 'Chi tiết hóa đơn',
    lineDescription: 'Khoản mục',
    lineOld: 'Chỉ số cũ',
    lineNew: 'Chỉ số mới',
    lineUsage: 'Số lượng',
    lineUnitPrice: 'Đơn giá',
    lineAmount: 'Thành tiền',
    rentLine: 'Tiền phòng',
    totalLabel: 'Tổng cộng',
    dueLabel: 'Hạn thanh toán',
    sentAtLabel: 'Đã gửi lúc',
    sendAction: 'Gửi mail',
    resendAction: 'Gửi lại mail',
    sending: 'Đang gửi…',
    sentToast: 'Đã gửi hóa đơn tới email khách thuê.',
    pdfAction: 'Tải PDF',
    paymentHeading: 'Cập nhật thanh toán',
    paymentLabel: 'Số tiền đã thu',
    paymentAction: 'Cập nhật',
    markPaidAction: 'Đánh dấu đã thanh toán',
    periodFilterAll: 'Mọi kỳ',
  },
  invoiceStatus: {
    draft: 'Bản nháp',
    sent: 'Đã gửi',
    unpaid: 'Chưa thanh toán',
    partiallyPaid: 'Thanh toán một phần',
    paid: 'Đã thanh toán',
  },
  service: {
    heading: 'Bảng giá dịch vụ',
    subtitle:
      'Đơn giá áp dụng cho hóa đơn mới. Hóa đơn đã phát hành giữ nguyên giá tại thời điểm chốt.',
    addAction: 'Thêm dịch vụ',
    editAction: 'Sửa dịch vụ',
    empty: 'Chưa cấu hình dịch vụ nào.',
    codeLabel: 'Mã dịch vụ',
    nameLabel: 'Tên dịch vụ',
    priceLabel: 'Đơn giá',
    unitLabel: 'Đơn vị tính',
    categoryLabel: 'Loại',
    activeLabel: 'Đang áp dụng',
    inactiveLabel: 'Tạm ngưng',
    deleteConfirm: 'Xóa dịch vụ này khỏi bảng giá?',
  },
  serviceUnit: {
    perKwh: 'VND/kWh',
    perCubicMeter: 'VND/m³',
    perRoom: 'VND/phòng',
    perPerson: 'VND/người',
    perMonth: 'VND/tháng',
  },
  serviceCategory: {
    metered: 'Theo chỉ số',
    fixed: 'Cố định',
  },
  user: {
    heading: 'Quản lý người dùng',
    empty: 'Chưa có tài khoản nào.',
    usernameLabel: 'Tên đăng nhập',
    emailLabel: 'Email',
    roleLabel: 'Vai trò',
    verifiedLabel: 'Xác minh',
    createdLabel: 'Ngày tạo',
    verified: 'Đã xác minh',
    unverified: 'Chưa xác minh',
    deleteConfirm: 'Xóa tài khoản này?',
  },
  lead: {
    heading: 'Yêu cầu tư vấn',
    empty: 'Chưa có yêu cầu nào.',
    nameLabel: 'Họ tên',
    phoneLabel: 'Số điện thoại',
    emailLabel: 'Email',
    messageLabel: 'Nội dung',
    roomLabel: 'Phòng quan tâm',
    statusLabel: 'Trạng thái',
    createdLabel: 'Thời gian gửi',
    namePlaceholder: 'Nguyễn Văn A',
    phonePlaceholder: '09xx xxx xxx',
    emailPlaceholder: 'ban@example.com',
    messagePlaceholder: 'Bạn quan tâm loại phòng nào, dự kiến chuyển vào khi nào?',
    submitAction: 'Gửi thông tin',
    deleteConfirm: 'Xóa yêu cầu tư vấn này?',
  },
  leadStatus: {
    new: 'Mới',
    contacted: 'Đã liên hệ',
    closed: 'Đã đóng',
  },
  tenant: {
    heading: 'Cổng thông tin khách thuê',
    contractHeading: 'Hợp đồng của bạn',
    roomHeading: 'Phòng của bạn',
    invoicesHeading: 'Lịch sử hóa đơn',
    invoicesEmpty: 'Chưa có hóa đơn nào cho hợp đồng này.',
    noContract: 'Tài khoản của bạn chưa được gắn với hợp đồng nào.',
    invoiceDetailAction: 'Xem chi tiết',
    invoiceRemainingLabel: 'Còn phải trả',
    navOverview: 'Mức sử dụng',
    navProfile: 'Hồ sơ của bạn',
    profilePageHeading: 'Hồ sơ của bạn',
    usageHeading: 'Mức sử dụng theo kỳ',
    usageEmpty: 'Chưa đủ dữ liệu để vẽ biểu đồ. Cần ít nhất một hóa đơn đã phát hành.',
    usageAverage: 'Trung bình',
    balanceHeading: 'Cần thanh toán',
    balanceOutstanding: 'Tổng cần thanh toán',
    balanceCurrent: 'Hóa đơn kỳ này',
    balancePrevious: 'Còn nợ kỳ trước',
    balanceDueDate: 'Hạn gần nhất',
    invoicePreviousDue: 'Còn nợ các kỳ trước',
    invoiceAmountDue: 'Tổng cần chuyển khoản',
    balanceCarryOver:
      'Số này gồm cả phần chưa trả hết của các kỳ trước, không chỉ riêng hóa đơn kỳ này.',
    usageLatest: 'Kỳ gần nhất',
    profileHeading: 'Thông tin của bạn',
    profileName: 'Họ và tên',
    profilePhone: 'Số điện thoại',
    profileEmail: 'Email',
    profileIdCard: 'CCCD/CMND',
    profileOccupants: 'Số người ở',
    profileOccupantsUnit: 'người',
    profileNote: 'Ghi chú',
  },
  errors: {
    generic: 'Có lỗi xảy ra. Vui lòng thử lại.',
    network: 'Không kết nối được máy chủ.',
    required: 'Vui lòng nhập đầy đủ thông tin bắt buộc.',
    notFoundPage: 'Không tìm thấy trang bạn yêu cầu.',
    forbiddenPage: 'Bạn không có quyền truy cập khu vực này.',
  },
} as const
