/**
 * Every user-facing string in the app. Components must never inline text.
 *
 * Grouped by the screen or component that renders them, so a translator (or a
 * future i18n layer) can move a whole group at once.
 */
export const STRINGS = {
  app: {
    title: 'Nhà Trọ An Cư',
    tagline: 'Hệ thống quản lý phòng trọ thông minh',
    shortName: 'An Cư',
  },
  health: {
    checking: 'Đang kiểm tra máy chủ…',
    online: 'Máy chủ hoạt động',
    offline: 'Không kết nối được máy chủ — backend đã chạy chưa?',
    versionLabel: 'phiên bản',
  },
  common: {
    save: 'Lưu',
    saving: 'Đang lưu…',
    cancel: 'Hủy',
    close: 'Đóng',
    edit: 'Sửa',
    delete: 'Xóa',
    deleting: 'Đang xóa…',
    confirmDelete: 'Bạn chắc chắn muốn xóa mục này?',
    add: 'Thêm',
    search: 'Tìm kiếm',
    loading: 'Đang tải…',
    retry: 'Thử lại',
    empty: 'Chưa có dữ liệu.',
    all: 'Tất cả',
    actions: 'Thao tác',
    submitting: 'Đang gửi…',
    updating: 'Đang cập nhật…',
    required: 'Bắt buộc',
    optional: 'Không bắt buộc',
    currencySuffix: 'đ',
    perMonth: '/tháng',
    unknown: '—',
  },
  nav: {
    home: 'Trang chủ',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    register: 'Đăng ký',
    adminArea: 'Trang quản trị',
    tenantArea: 'Cổng khách thuê',
    dashboard: 'Tổng quan',
    rooms: 'Quản lý phòng',
    contracts: 'Hợp đồng',
    meters: 'Ghi chỉ số',
    invoices: 'Hóa đơn',
    services: 'Bảng giá dịch vụ',
    users: 'Người dùng',
    leads: 'Yêu cầu tư vấn',
  },
  home: {
    heroEyebrow: 'Ngõ 42 Vũ Trọng Phụng, Thanh Xuân, Hà Nội',
    heroTitle: 'Tiền nhà tính ra từng dòng.',
    heroBody:
      'Mỗi tháng bạn nhận đúng bảng tính dưới đây qua email: chỉ số điện nước cũ và mới, đơn giá, thành tiền. Không có khoản nào bạn không tự cộng lại được.',
    heroPrimaryAction: 'Xem phòng còn trống',
    heroSecondaryAction: 'Đặt lịch xem phòng',
    ledgerCaption: 'Hóa đơn tháng 8 — phòng 202',
    ledgerPeriodLabel: 'Kỳ 08/2026',
    ledgerNote:
      'Đây là phép tính thật hệ thống chạy, với đơn giá đang áp dụng. Khách thuê đăng nhập xem lại được mọi kỳ đã chốt.',
    ledgerRowElectric: 'Điện',
    ledgerRowWater: 'Nước',
    ledgerRowRent: 'Tiền phòng',
    ledgerRowService: 'Dịch vụ',
    ledgerRowTotal: 'Cộng',
    ledgerRentWork: 'Giá thuê cố định theo hợp đồng',
    ledgerServiceWork: 'Internet, an ninh & PCCC, vệ sinh',
    amenitiesHeading: 'Tiện ích cốt lõi',
    amenitiesBody: 'Ba thứ chúng tôi đầu tư trước khi nghĩ tới bất cứ điều gì khác.',
    fireTitle: 'Hệ thống PCCC đạt chuẩn',
    fireBody:
      'Cảm biến khói tự động từng tầng, vòi phun nước ngầm, lối thoát hiểm thông suốt và bình chữa cháy được kiểm định định kỳ.',
    internetTitle: 'Internet cáp quang & Wifi mesh',
    internetBody:
      'Hạ tầng cáp quang riêng cho từng phòng, băng thông cam kết ổn định, Wifi mesh phủ sóng toàn tòa nhà cho làm việc và giải trí.',
    otherTitle: 'An ninh & tiện ích chung',
    otherBody:
      'Khu để xe có camera 24/7 và khóa vân tay, dịch vụ vệ sinh không gian chung, khu giặt sấy ngay trong tòa nhà.',
    roomsHeading: 'Phòng mẫu',
    roomsBody: 'Bấm vào một phòng để xem toàn bộ hình ảnh và thông tin chi tiết.',
    roomsEmpty: 'Hiện chưa có phòng nào được đăng.',
    contactHeading: 'Đăng ký giữ chỗ',
    contactBody:
      'Để lại thông tin, chúng tôi sẽ gọi lại trong ngày để hẹn lịch xem phòng.',
    footerNote: 'Hệ thống quản lý phòng trọ thông minh.',
  },
  room: {
    areaLabel: 'Diện tích',
    areaUnit: 'm²',
    floorLabel: 'Tầng',
    typeLabel: 'Loại phòng',
    priceLabel: 'Giá thuê',
    amenitiesLabel: 'Tiện nghi',
    numberLabel: 'Số phòng',
    statusLabel: 'Trạng thái',
    descriptionLabel: 'Mô tả',
    imagesLabel: 'Bộ sưu tập ảnh',
    imageUrlPlaceholder: 'Dán link ảnh rồi bấm Thêm',
    addImage: 'Thêm ảnh',
    removeImage: 'Xóa ảnh',
    suggestedImages: 'Ảnh gợi ý',
    noImages: 'Chưa có ảnh nào.',
    detailHeading: 'Chi tiết phòng',
    bookThisRoom: 'Đặt lịch xem phòng này',
    galleryPrev: 'Ảnh trước',
    galleryNext: 'Ảnh sau',
    heading: 'Danh sách phòng',
    addAction: 'Thêm phòng',
    editAction: 'Sửa phòng',
    empty: 'Chưa có phòng nào. Thêm phòng đầu tiên.',
    searchPlaceholder: 'Tìm theo số phòng…',
    deleteConfirm: 'Xóa phòng này? Thao tác không thể hoàn tác.',
  },
  roomStatus: {
    available: 'Còn trống',
    occupied: 'Đang thuê',
    maintenance: 'Bảo trì',
    overdue: 'Chậm đóng tiền',
  },
  roomType: {
    studio: 'Studio',
    oneBedroom: '1 phòng ngủ',
    twoBedroom: '2 phòng ngủ',
  },
  auth: {
    loginHeading: 'Đăng nhập',
    loginBody: 'Dành cho quản trị viên và khách thuê đã xác minh email.',
    registerHeading: 'Đăng ký tài khoản quản trị',
    registerBody: 'Tạo tài khoản quản trị viên để truy cập hệ thống.',
    usernameLabel: 'Tên đăng nhập',
    usernamePlaceholder: 'vd: quanly01',
    emailLabel: 'Email',
    emailPlaceholder: 'ban@example.com',
    passwordLabel: 'Mật khẩu',
    passwordPlaceholder: 'Tối thiểu 6 ký tự',
    loginAction: 'Đăng nhập',
    loggingIn: 'Đang đăng nhập…',
    registerAction: 'Tạo tài khoản',
    registering: 'Đang tạo tài khoản…',
    toRegister: 'Chưa có tài khoản? Đăng ký',
    toLogin: 'Đã có tài khoản? Đăng nhập',
    signedInAs: 'Đang đăng nhập',
    verifyHeading: 'Xác minh email',
    verifying: 'Đang xác minh…',
    verifySuccess: 'Email đã được xác minh. Bạn có thể đăng nhập ngay.',
    verifyMissingToken: 'Liên kết xác minh không hợp lệ.',
    goToLogin: 'Tới trang đăng nhập',
    resendAction: 'Gửi lại email xác minh',
    resending: 'Đang gửi…',
    resendSent: 'Đã gửi lại email xác minh.',
  },
  role: {
    admin: 'Quản trị viên',
    manager: 'Quản lý',
    tenant: 'Khách thuê',
  },
  dashboard: {
    heading: 'Tổng quan kinh doanh',
    subtitle: 'Tình hình phòng ốc và dòng tiền theo thời gian thực.',
    totalRooms: 'Tổng số phòng',
    availableRooms: 'Phòng trống',
    occupiedRooms: 'Đang cho thuê',
    maintenanceRooms: 'Đang bảo trì',
    activeContracts: 'Hợp đồng hiệu lực',
    expiringContracts: 'Sắp hết hạn',
    unpaidInvoices: 'Hóa đơn chưa thu',
    outstandingAmount: 'Công nợ còn lại',
    monthRevenue: 'Doanh thu tháng này',
    gridHeading: 'Sơ đồ phòng',
    gridLegend: 'Chú thích',
    gridEmpty: 'Chưa có phòng nào để hiển thị.',
    revenueHeading: 'Doanh thu theo tháng',
    revenueRoom: 'Tiền phòng',
    revenueService: 'Tiền dịch vụ',
    revenueCollected: 'Đã thu',
    rangeMonth: 'Tháng này',
    rangeQuarter: 'Quý này',
    rangeYear: '12 tháng gần nhất',
    tenantLabel: 'Khách thuê',
    contractEndLabel: 'Hạn hợp đồng',
    vacant: 'Đang trống',
  },
  contract: {
    heading: 'Hợp đồng cho thuê',
    addAction: 'Tạo hợp đồng',
    editAction: 'Sửa hợp đồng',
    empty: 'Chưa có hợp đồng nào.',
    roomLabel: 'Phòng',
    tenantNameLabel: 'Họ tên khách thuê',
    idCardLabel: 'Số CCCD',
    phoneLabel: 'Số điện thoại',
    emailLabel: 'Email',
    startLabel: 'Ngày bắt đầu',
    endLabel: 'Ngày hết hạn',
    depositLabel: 'Tiền cọc',
    cycleLabel: 'Kỳ thanh toán',
    occupantsLabel: 'Số người ở',
    noteLabel: 'Ghi chú',
    statusLabel: 'Trạng thái',
    emailVerified: 'Email đã xác minh',
    emailUnverified: 'Email chưa xác minh',
    deleteConfirm: 'Thanh lý và xóa hợp đồng này? Phòng sẽ trở về trạng thái trống.',
    selectRoom: 'Chọn phòng',
    accountNote:
      'Hệ thống sẽ tự tạo tài khoản khách thuê: đăng nhập bằng email, mật khẩu mặc định là số điện thoại.',
  },
  contractStatus: {
    active: 'Đang hiệu lực',
    expiring: 'Sắp hết hạn',
    terminated: 'Đã thanh lý',
    overdue: 'Quá hạn đóng tiền',
  },
  paymentCycle: {
    monthly: 'Hàng tháng',
    quarterly: 'Mỗi 3 tháng',
  },
  meter: {
    heading: 'Ghi chỉ số điện nước',
    subtitle: 'Nhập chỉ số cuối kỳ cho từng phòng. Hóa đơn được tạo ngay khi ghi đủ hai chỉ số.',
    periodLabel: 'Kỳ ghi',
    searchPlaceholder: 'Tìm theo số phòng hoặc tên khách…',
    columnRoom: 'Phòng',
    columnTenant: 'Khách thuê',
    columnElectric: 'Điện (kWh)',
    columnWater: 'Nước (m³)',
    oldLabel: 'Cũ',
    newLabel: 'Mới',
    usageLabel: 'Tiêu thụ',
    saveAction: 'Lưu',
    savedLabel: 'Đã lưu',
    invoiceCreated: 'Đã tạo hóa đơn',
    empty: 'Không có phòng nào khớp bộ lọc.',
    tabAll: 'Tất cả',
    tabMissingElectric: 'Chưa ghi Điện',
    tabMissingWater: 'Chưa ghi Nước',
    tabComplete: 'Đã ghi xong',
    belowPrevious: 'Chỉ số mới không được nhỏ hơn chỉ số cũ.',
  },
  invoice: {
    heading: 'Hóa đơn',
    empty: 'Chưa có hóa đơn nào.',
    columnRoom: 'Phòng',
    columnTenant: 'Khách thuê',
    columnPeriod: 'Kỳ',
    columnTotal: 'Tổng tiền',
    columnPaid: 'Đã thanh toán',
    columnStatus: 'Trạng thái',
    detailHeading: 'Chi tiết hóa đơn',
    lineDescription: 'Khoản mục',
    lineOld: 'Chỉ số cũ',
    lineNew: 'Chỉ số mới',
    lineUsage: 'Số lượng',
    lineUnitPrice: 'Đơn giá',
    lineAmount: 'Thành tiền',
    rentLine: 'Tiền phòng',
    totalLabel: 'Tổng cộng',
    dueLabel: 'Hạn thanh toán',
    sentAtLabel: 'Đã gửi lúc',
    sendAction: 'Gửi mail',
    resendAction: 'Gửi lại mail',
    sending: 'Đang gửi…',
    sentToast: 'Đã gửi hóa đơn tới email khách thuê.',
    pdfAction: 'Tải PDF',
    paymentHeading: 'Cập nhật thanh toán',
    paymentLabel: 'Số tiền đã thu',
    paymentAction: 'Cập nhật',
    markPaidAction: 'Đánh dấu đã thanh toán',
    periodFilterAll: 'Mọi kỳ',
  },
  invoiceStatus: {
    draft: 'Bản nháp',
    sent: 'Đã gửi',
    unpaid: 'Chưa thanh toán',
    partiallyPaid: 'Thanh toán một phần',
    paid: 'Đã thanh toán',
  },
  service: {
    heading: 'Bảng giá dịch vụ',
    subtitle:
      'Đơn giá áp dụng cho hóa đơn mới. Hóa đơn đã phát hành giữ nguyên giá tại thời điểm chốt.',
    addAction: 'Thêm dịch vụ',
    editAction: 'Sửa dịch vụ',
    empty: 'Chưa cấu hình dịch vụ nào.',
    codeLabel: 'Mã dịch vụ',
    nameLabel: 'Tên dịch vụ',
    priceLabel: 'Đơn giá',
    unitLabel: 'Đơn vị tính',
    categoryLabel: 'Loại',
    activeLabel: 'Đang áp dụng',
    inactiveLabel: 'Tạm ngưng',
    deleteConfirm: 'Xóa dịch vụ này khỏi bảng giá?',
  },
  serviceUnit: {
    perKwh: 'VND/kWh',
    perCubicMeter: 'VND/m³',
    perRoom: 'VND/phòng',
    perPerson: 'VND/người',
    perMonth: 'VND/tháng',
  },
  serviceCategory: {
    metered: 'Theo chỉ số',
    fixed: 'Cố định',
  },
  user: {
    heading: 'Quản lý người dùng',
    empty: 'Chưa có tài khoản nào.',
    usernameLabel: 'Tên đăng nhập',
    emailLabel: 'Email',
    roleLabel: 'Vai trò',
    verifiedLabel: 'Xác minh',
    createdLabel: 'Ngày tạo',
    verified: 'Đã xác minh',
    unverified: 'Chưa xác minh',
    deleteConfirm: 'Xóa tài khoản này?',
  },
  lead: {
    heading: 'Yêu cầu tư vấn',
    empty: 'Chưa có yêu cầu nào.',
    nameLabel: 'Họ tên',
    phoneLabel: 'Số điện thoại',
    emailLabel: 'Email',
    messageLabel: 'Nội dung',
    roomLabel: 'Phòng quan tâm',
    statusLabel: 'Trạng thái',
    createdLabel: 'Thời gian gửi',
    namePlaceholder: 'Nguyễn Văn A',
    phonePlaceholder: '09xx xxx xxx',
    emailPlaceholder: 'ban@example.com',
    messagePlaceholder: 'Bạn quan tâm loại phòng nào, dự kiến chuyển vào khi nào?',
    submitAction: 'Gửi thông tin',
    deleteConfirm: 'Xóa yêu cầu tư vấn này?',
  },
  leadStatus: {
    new: 'Mới',
    contacted: 'Đã liên hệ',
    closed: 'Đã đóng',
  },
  tenant: {
    heading: 'Cổng thông tin khách thuê',
    contractHeading: 'Hợp đồng của bạn',
    roomHeading: 'Phòng của bạn',
    invoicesHeading: 'Lịch sử hóa đơn',
    invoicesEmpty: 'Chưa có hóa đơn nào cho hợp đồng này.',
    noContract: 'Tài khoản của bạn chưa được gắn với hợp đồng nào.',
  },
  errors: {
    generic: 'Có lỗi xảy ra. Vui lòng thử lại.',
    network: 'Không kết nối được máy chủ.',
    required: 'Vui lòng nhập đầy đủ thông tin bắt buộc.',
    notFoundPage: 'Không tìm thấy trang bạn yêu cầu.',
    forbiddenPage: 'Bạn không có quyền truy cập khu vực này.',
  },
} as const
